# Generated by Django 2.2.28 on 2022-10-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_addresspwxwqpywoo'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresspwxwqpywoo',
            name='ca',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
